[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  me-no-dev/ESP Async WebServer @ ^3.6.0
  me-no-dev/AsyncTCP @ ^1.1.1
build_flags = -D PARKING_VERSION=\"0.1.1\"
